// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFX-dnCagIbudt0D_1AYA1LHs9FsM1kXc',
    appId: '1:847186486454:web:5945d2bac447a610fb3217',
    messagingSenderId: '847186486454',
    projectId: 'exam-papers-and-materials',
    authDomain: 'exam-papers-and-materials.firebaseapp.com',
    storageBucket: 'exam-papers-and-materials.firebasestorage.app',
    measurementId: 'G-FVBHMD9JBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZPi1dvNfhL17pPtRlZixY30YvIS2kyPY',
    appId: '1:847186486454:android:75288fc8ac3743fefb3217',
    messagingSenderId: '847186486454',
    projectId: 'exam-papers-and-materials',
    storageBucket: 'exam-papers-and-materials.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlTSbExDg8qtR1DVBp07FnbGLBxX4U0OE',
    appId: '1:847186486454:ios:24e6254e15ef39c6fb3217',
    messagingSenderId: '847186486454',
    projectId: 'exam-papers-and-materials',
    storageBucket: 'exam-papers-and-materials.firebasestorage.app',
    iosBundleId: 'com.example.govtExamPapers',
  );
}
